[package]
name = "xdb-shuttle"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
log = "0.4.29"
pretty_assertions = "1.4.1"
shuttle = { git = "https://github.com/awslabs/shuttle.git", branch="main" }
xdb = {path = "../xdb/", features = ["shuttle"]}

[dependencies]
env_logger = "0.11.8"
