[package]
name = "xdb-server"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24.0", features = ["latest_stable_rust"] }
env_logger = "0.11.8"
log = "0.4.29"
xdb = {path="../xdb/"}
