[package]
name = "xdb-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
xdb = {path="../xdb/"}
env_logger = "0.11.8"
arbitrary = { version = "1.4.2", features = ["derive"] }
rand = "0.9.2"
log = "0.4.29"
